USE [UploadFiles]
GO

/****** Object:  Table [dbo].[TRANSACTION_DATA]    Script Date: 10/7/2024 5:36:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRANSACTION_DATA](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TRANSACTION_ID] [nvarchar](50) NOT NULL,
	[ACCOUNT_NO] [nvarchar](30) NOT NULL,
	[AMOUNT] [decimal](18, 2) NOT NULL,
	[CURRENCY_CODE] [nvarchar](10) NOT NULL,
	[TRANSACTION_DATE] [datetime] NOT NULL,
	[STATUS] [nvarchar](20) NOT NULL,
	[FILE_FORMATS] [nchar](3) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_TRANSACTION_DATA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


