USE [UploadFiles]
GO

/****** Object:  Table [dbo].[TRANSACTION_LOG]    Script Date: 10/7/2024 5:42:05 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRANSACTION_LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SERVICE_NAME] [nvarchar](100) NOT NULL,
	[STATUS_CODE] [nvarchar](3) NOT NULL,
	[STATUS_NAME] [nvarchar](20) NOT NULL,
	[CREATED_BY] [nvarchar](100) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[UPDATED_BY] [nvarchar](100) NULL,
	[UPDATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_TRANSACTION_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


